dogtools/dog

Dogfile.yml
=> Add dog's own Dogfile

dog/exec.go, main.go
=> Switch time measurement, defined at task

.travis.yml
=> Add .travis.yml file for CI

dog/parser.go
=> Allow multiple Dogfiles per directory

dog/parser.go
You can save some line by removing the if statement. Whether err is nil or not you´re going to return it anyway.
=> Remove unnecessary code

main.go
=> Don't crash if there is no Dogfile or if Dogfile can't be parsed

DOGFILE_SPEC.md, dog/task.go
=> Rename type to exec

executor/executor.go, main.go, scripts/test-dogfiles.sh, testdata/Dogfile-mustfail.yml, testdata/Dogfile-sh.yml, types/event.go
This uses a channel to take care of events generated by task execution.
Also makes the application exit with same status code as the task.
This closes #47 
This closes #50
=> WIP First approach of event channel

execute/executor.go, execute/runner.go, types/event.go
Adds elapsed time to the footer of each task execution
=> Always measure elapsed time and print after executing

main.go
=> Vertically align descriptions

execute/executor.go, execute/runner.go, parser/parser.go, types/task.go
This adds cycle detection.
It is a WIP, also want to add some test cases.
It would be super helpful if you can test it also @xsb 
This closes #56
=> Cycle detection

DOGFILE_SPEC.md, Dogfile.yml, cli.go, execute/runner.go, main.go, parser/parser.go, types/task.go
=> Provide Environment Variables to tasks

Dogfile.yml, execute/executor.go, parser/parser.go, types/task.go
=> Workdir directive

DOGFILE_SPEC.md, README.md
=> Release v0.1.0

DOGFILE_SPEC.md
=> Improve Registers documentation

execute/runner.go, main.go
=> Allow env vars with the = symbol in its value

parser/parser.go, testdata/Dogfile-bash.json
=> Parse both json and yml

cli.go
=> Don't list tasks without description

execute/executor.go
=> Accept commands which read user input

cli.go, main.go
=> Adds ability to specify workdir from the cli.

DOGFILE_SPEC.md
Update Dogfile Spec based on what we decided in https://github.com/dogtools/dog/issues/5#issuecomment-239442493
=> Fix params documentation in the Spec

DOGFILE_SPEC.md, Dogfile.yml, execute/executor.go, execute/runner.go
=> Remove Windows support

extras/dog.bashcompletion
Hi I've created a bash completion script for dog.
I've put it under the `extras/` folder but I'm not sure if it should be the place. I'm open to suggestions.
=> Create bash completion for Dog.

DOGFILE_SPEC.md
=> Add timeout to the Dogfile Spec

DOGFILE_SPEC.md, chain.go, run/run.go, testdata/Dogfile-nodejs.yml
=> Create Node.js runner

DOGFILE_SPEC.md, Dogfile.yml, chain.go, parse.go, task.go, testdata/Dogfile-registers.yml
=> Implement the 'registers' feature
